version: '3.7'
services:
  kasm_chrome:
    image: kasmweb/chrome:latest
    ports:
      - "8001:8001"
    environment:
      - KASM_GPU=false
      - KASM_VNC_PASSWORD=set0ings
    networks:
      - kasm-net
networks:
  kasm-net:
    driver: bridge
